/**
 * Story 8.2 (FR-Q-03): IS 2500 (Part 1):2000 / ISO 2859-1:1999 single-sampling tables as DATA.
 *
 * Table I (sample-size code letters), Table II-A (single sampling, normal inspection), Table II-B
 * (tightened) and Table II-C (reduced) are transcribed below as literal cells; no plan is computed by
 * formula (Annex requirement 1). Arrow cells are kept as 'down' / 'up' exactly as printed and are
 * resolved by singleSamplingPlan() per the standard's rule: follow the arrow to the first plan cell
 * in the same column and use THAT row's sample size.
 *
 * Transcription notes (verified against the story's pinned anchor cells, Dev Notes Table 3):
 * - Tables II-A and II-C carry eleven plan diagonals (Ac 0, 1, 2, 3, 5, 7, 10, 14, 21, 30, 44 on
 *   normal; the gapped Ac/Re pairs on reduced); Table II-B carries ten (0, 1, 2, 3, 5, 8, 12, 18,
 *   27, 41). The Ac = 0 diagonal passes through G at AQL 1.0 on normal and reduced, and through H at
 *   AQL 1.0 on tightened.
 * - The standard prints a supplementary code letter S (n = 3150) at the bottom-left of Table II-B
 *   for AQL 0.010 and 0.015 at letter R. This module keeps the 16-letter vocabulary the story
 *   pins (A to R, no I or O) and records those corner cells - R at AQL 0.010 and 0.015 on II-A and
 *   II-C, and R at AQL 0.010, 0.015 and 0.025 on II-B - as Ac 0 / Re 1 at n = 2000, the tightest
 *   plan the 16-letter tables offer; a down arrow with no plan beneath it would otherwise be
 *   unresolvable.
 * - Sample sizes: A 2, B 3, C 5, D 8, E 13, F 20, G 32, H 50, J 80, K 125, L 200, M 315, N 500,
 *   P 800, Q 1250, R 2000 (normal and tightened); reduced 2, 2, 2, 3, 5, 8, 13, 20, 32, 50, 80,
 *   125, 200, 315, 500, 800.
 *
 * Every value is exact: AQLs are decimal STRINGS (never Number), integers are only ever the table's
 * own integers (sample size, Ac, Re). Nothing in this module reaches the database.
 */

export const STANDARD_REF = 'IS 2500 (Part 1):2000 / ISO 2859-1:1999';

/** The 26 preferred AQL values, as the standard prints them (column order). */
export const PREFERRED_AQLS = [
  '0.010',
  '0.015',
  '0.025',
  '0.040',
  '0.065',
  '0.10',
  '0.15',
  '0.25',
  '0.40',
  '0.65',
  '1.0',
  '1.5',
  '2.5',
  '4.0',
  '6.5',
  '10',
  '15',
  '25',
  '40',
  '65',
  '100',
  '150',
  '250',
  '400',
  '650',
  '1000',
] as const;
export type PreferredAql = (typeof PREFERRED_AQLS)[number];

export const INSPECTION_LEVELS = ['I', 'II', 'III', 'S-1', 'S-2', 'S-3', 'S-4'] as const;
export type InspectionLevel = (typeof INSPECTION_LEVELS)[number];

export const CODE_LETTERS = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'M',
  'N',
  'P',
  'Q',
  'R',
] as const;
export type CodeLetter = (typeof CODE_LETTERS)[number];

export type Severity = 'normal' | 'tightened' | 'reduced';

export const SAMPLE_SIZES: Readonly<Record<CodeLetter, number>> = {
  A: 2,
  B: 3,
  C: 5,
  D: 8,
  E: 13,
  F: 20,
  G: 32,
  H: 50,
  J: 80,
  K: 125,
  L: 200,
  M: 315,
  N: 500,
  P: 800,
  Q: 1250,
  R: 2000,
};

export const REDUCED_SAMPLE_SIZES: Readonly<Record<CodeLetter, number>> = {
  A: 2,
  B: 2,
  C: 2,
  D: 3,
  E: 5,
  F: 8,
  G: 13,
  H: 20,
  J: 32,
  K: 50,
  L: 80,
  M: 125,
  N: 200,
  P: 315,
  Q: 500,
  R: 800,
};

/** Table I lot-size bands, inclusive; the last band is open-ended (max null). */
export const LOT_SIZE_BANDS: readonly { min: number; max: number | null }[] = [
  { min: 2, max: 8 },
  { min: 9, max: 15 },
  { min: 16, max: 25 },
  { min: 26, max: 50 },
  { min: 51, max: 90 },
  { min: 91, max: 150 },
  { min: 151, max: 280 },
  { min: 281, max: 500 },
  { min: 501, max: 1200 },
  { min: 1201, max: 3200 },
  { min: 3201, max: 10000 },
  { min: 10001, max: 35000 },
  { min: 35001, max: 150000 },
  { min: 150001, max: 500000 },
  { min: 500001, max: null },
];

/** Table I: one code letter per band (top to bottom) for every inspection level. */
export const CODE_LETTER_TABLE: Readonly<Record<InspectionLevel, readonly CodeLetter[]>> = {
  I: ['A', 'A', 'B', 'C', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N'],
  II: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q'],
  III: ['B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R'],
  'S-1': ['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D'],
  'S-2': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D', 'E', 'E', 'E'],
  'S-3': ['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'F', 'F', 'G', 'G', 'H'],
  'S-4': ['A', 'A', 'B', 'C', 'C', 'D', 'E', 'E', 'F', 'G', 'G', 'H', 'J', 'J', 'K'],
};

export type PlanCell = { ac: number; re: number } | 'down' | 'up';

export const TABLE_II_A: Readonly<Record<CodeLetter, readonly PlanCell[]>> = {
  A: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
  ],
  B: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
  ],
  C: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
  ],
  D: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
  ],
  E: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
  ],
  F: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
  ],
  G: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  H: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  J: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  K: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  L: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  M: [
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  N: [
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  P: [
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  Q: [
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  R: [
    { ac: 0, re: 1 },
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 7, re: 8 },
    { ac: 10, re: 11 },
    { ac: 14, re: 15 },
    { ac: 21, re: 22 },
    { ac: 30, re: 31 },
    { ac: 44, re: 45 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
};

export const TABLE_II_B: Readonly<Record<CodeLetter, readonly PlanCell[]>> = {
  A: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
  ],
  B: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
  ],
  C: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
  ],
  D: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
  ],
  E: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
  ],
  F: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
  ],
  G: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  H: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  J: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  K: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  L: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  M: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  N: [
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  P: [
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  Q: [
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  R: [
    { ac: 0, re: 1 },
    { ac: 0, re: 1 },
    { ac: 0, re: 1 },
    { ac: 1, re: 2 },
    { ac: 2, re: 3 },
    { ac: 3, re: 4 },
    { ac: 5, re: 6 },
    { ac: 8, re: 9 },
    { ac: 12, re: 13 },
    { ac: 18, re: 19 },
    { ac: 27, re: 28 },
    { ac: 41, re: 42 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
};

export const TABLE_II_C: Readonly<Record<CodeLetter, readonly PlanCell[]>> = {
  A: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
  ],
  B: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
  ],
  C: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
  ],
  D: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
  ],
  E: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
  ],
  F: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
  ],
  G: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  H: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  J: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  K: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  L: [
    'down',
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  M: [
    'down',
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  N: [
    'down',
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  P: [
    'down',
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  Q: [
    'down',
    'down',
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
  R: [
    { ac: 0, re: 1 },
    { ac: 0, re: 1 },
    { ac: 0, re: 2 },
    { ac: 1, re: 3 },
    { ac: 1, re: 4 },
    { ac: 2, re: 5 },
    { ac: 3, re: 6 },
    { ac: 5, re: 8 },
    { ac: 7, re: 10 },
    { ac: 10, re: 13 },
    { ac: 14, re: 17 },
    { ac: 21, re: 24 },
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
    'up',
  ],
};

export const TABLES_BY_SEVERITY: Readonly<
  Record<Severity, Readonly<Record<CodeLetter, readonly PlanCell[]>>>
> = {
  normal: TABLE_II_A,
  tightened: TABLE_II_B,
  reduced: TABLE_II_C,
};

const DECIMAL_REGEX = /^(\d+)(?:\.(\d+))?$/;

/**
 * Normalizes a decimal STRING (for example '1.000', '1', '1.0', '0.10', '00.1') to the preferred
 * AQL key it denotes, or null when it is not one of the standard's 26 preferred values. Pure string
 * arithmetic: leading integer zeros and trailing fraction zeros are stripped and the result is
 * compared against every preferred value normalized the same way. Never uses Number.
 */
export function canonicalAql(value: string): PreferredAql | null {
  const normalized = normalizeDecimal(value);
  if (normalized === null) return null;
  for (const aql of PREFERRED_AQLS) {
    if (normalizeDecimal(aql) === normalized) return aql;
  }
  return null;
}

function normalizeDecimal(value: string): string | null {
  if (typeof value !== 'string') return null;
  const m = DECIMAL_REGEX.exec(value.trim());
  if (!m) return null;
  const int = m[1]!.replace(/^0+(?=\d)/, '');
  const frac = (m[2] ?? '').replace(/0+$/, '');
  return frac.length > 0 ? `${int}.${frac}` : int;
}

export function isInspectionLevel(value: unknown): value is InspectionLevel {
  return typeof value === 'string' && (INSPECTION_LEVELS as readonly string[]).includes(value);
}

export function isCodeLetter(value: unknown): value is CodeLetter {
  return typeof value === 'string' && (CODE_LETTERS as readonly string[]).includes(value);
}

/**
 * Table I lookup. Returns null when the lot size is below the first band (2), which the caller
 * treats as "inspect the whole lot" (Annex requirement 4).
 */
export function codeLetterFor(lotSize: number, level: InspectionLevel): CodeLetter | null {
  if (!Number.isSafeInteger(lotSize) || lotSize < LOT_SIZE_BANDS[0]!.min) return null;
  const letters = CODE_LETTER_TABLE[level];
  for (let i = 0; i < LOT_SIZE_BANDS.length; i += 1) {
    const band = LOT_SIZE_BANDS[i]!;
    if (lotSize >= band.min && (band.max === null || lotSize <= band.max)) return letters[i]!;
  }
  return null;
}

export interface SingleSamplingPlan {
  code_letter: CodeLetter;
  /** The letter whose row supplied the plan after arrow resolution (equals code_letter when no arrow). */
  resolved_letter: CodeLetter;
  sample_size: number;
  ac: number;
  re: number;
}

/**
 * Tables II-A / II-B / II-C lookup with arrow resolution: an arrow cell is followed down (or up)
 * the same AQL column to the first plan cell, and that row's sample size is used. Returns null
 * only if a column were entirely arrows, which the transcription guarantees never happens.
 */
export function singleSamplingPlan(
  letter: CodeLetter,
  aql: PreferredAql,
  severity: Severity,
): SingleSamplingPlan | null {
  const column = PREFERRED_AQLS.indexOf(aql);
  if (column < 0) return null;
  const table = TABLES_BY_SEVERITY[severity];
  const sizes = severity === 'reduced' ? REDUCED_SAMPLE_SIZES : SAMPLE_SIZES;
  let row = CODE_LETTERS.indexOf(letter);
  let cell = table[letter]![column]!;
  let guard = 0;
  while (typeof cell === 'string') {
    row += cell === 'down' ? 1 : -1;
    guard += 1;
    if (row < 0 || row >= CODE_LETTERS.length || guard > CODE_LETTERS.length) return null;
    cell = table[CODE_LETTERS[row]!]![column]!;
  }
  const resolved = CODE_LETTERS[row]!;
  return {
    code_letter: letter,
    resolved_letter: resolved,
    sample_size: sizes[resolved],
    ac: cell.ac,
    re: cell.re,
  };
}

/** The preferred AQL one step tighter (smaller) than `aql`, or null at the first column. */
export function tighterAql(aql: PreferredAql): PreferredAql | null {
  const column = PREFERRED_AQLS.indexOf(aql);
  return column > 0 ? PREFERRED_AQLS[column - 1]! : null;
}
