[main]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=4
repo1-retention-diff=30
repo1-cipher-type=aes-256-cbc

[main:pg1]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
pg1-socket-path=/var/run/postgresql

[global]
log-level-console=info
log-level-file=detail
compress-type=zstd
compress-level=3
start-fast=y
delta=y

[global:archive-push]
archive-push-queue-max=1GB
